version: "3.8"

services:
  # excalidraw-room backend
  backend:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - excalidraw-network
    restart: unless-stopped

  # excalidraw-board frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.prod
    container_name: excalidraw-board
    environment:
      - VITE_WEBSOCKET_SERVER_URL=wss://${SERVER_HOST:-localhost}:30443
      - VITE_DEBUG_WEBSOCKET=${VITE_DEBUG_WEBSOCKET:-false}
    networks:
      - excalidraw-network
    depends_on:
      - backend
    restart: unless-stopped

  # nginx reverse proxy with HTTPS
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: excalidraw-nginx
    ports:
      - "30080:80"
      - "30443:443"
    environment:
      - SERVER_HOST=${SERVER_HOST:-localhost}
    networks:
      - excalidraw-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped


networks:
  excalidraw-network:
    driver: bridge
