version: "3.8"

services:
  # excalidraw-room backend
  backend-dev:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room-dev
    environment:
      - NODE_ENV=development
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - excalidraw-dev-network
    restart: unless-stopped

  # excalidraw-board frontend (development mode with hot reload)
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    container_name: excalidraw-board-dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - excalidraw-dev-network
    depends_on:
      - backend-dev
    restart: unless-stopped

networks:
  excalidraw-dev-network:
    driver: bridge
