global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'excalidraw-frontend'
    static_configs:
      - targets: ['frontend:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'excalidraw-room'
    static_configs:
      - targets: ['excalidraw-room:80']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:9113']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093